apiVersion: v1
items:
- apiVersion: v1
  kind: PersistentVolumeClaim
  metadata:
    annotations:
      kubectl.kubernetes.io/last-applied-configuration: |
        {"apiVersion":"v1","kind":"PersistentVolumeClaim","metadata":{"annotations":{},"name":"gemma3-cache","namespace":"vllm-chat"},"spec":{"accessModes":["ReadWriteOnce"],"resources":{"requests":{"storage":"30Gi"}},"storageClassName":"local-path"}}
      pv.kubernetes.io/bind-completed: "yes"
      pv.kubernetes.io/bound-by-controller: "yes"
      volume.beta.kubernetes.io/storage-provisioner: rancher.io/local-path
      volume.kubernetes.io/selected-node: srv-datalab
      volume.kubernetes.io/storage-provisioner: rancher.io/local-path
    creationTimestamp: "2026-01-03T22:00:32Z"
    finalizers:
    - kubernetes.io/pvc-protection
    name: gemma3-cache
    namespace: vllm-chat
    resourceVersion: "57378594"
    uid: ac704e55-ec08-4bbf-b475-b0a3da1317ec
  spec:
    accessModes:
    - ReadWriteOnce
    resources:
      requests:
        storage: 30Gi
    storageClassName: local-path
    volumeMode: Filesystem
    volumeName: pvc-ac704e55-ec08-4bbf-b475-b0a3da1317ec
  status:
    accessModes:
    - ReadWriteOnce
    capacity:
      storage: 30Gi
    phase: Bound
- apiVersion: v1
  kind: PersistentVolumeClaim
  metadata:
    annotations:
      kubectl.kubernetes.io/last-applied-configuration: |
        {"apiVersion":"v1","kind":"PersistentVolumeClaim","metadata":{"annotations":{},"name":"gpt-oss-cache","namespace":"vllm-chat"},"spec":{"accessModes":["ReadWriteOnce"],"resources":{"requests":{"storage":"100Gi"}},"storageClassName":"local-path"}}
      pv.kubernetes.io/bind-completed: "yes"
      pv.kubernetes.io/bound-by-controller: "yes"
      volume.beta.kubernetes.io/storage-provisioner: rancher.io/local-path
      volume.kubernetes.io/selected-node: srv-datalab
      volume.kubernetes.io/storage-provisioner: rancher.io/local-path
    creationTimestamp: "2025-10-31T14:42:52Z"
    finalizers:
    - kubernetes.io/pvc-protection
    name: gpt-oss-cache
    namespace: vllm-chat
    resourceVersion: "40634542"
    uid: a7016676-4c44-4f34-8c02-68908353555a
  spec:
    accessModes:
    - ReadWriteOnce
    resources:
      requests:
        storage: 100Gi
    storageClassName: local-path
    volumeMode: Filesystem
    volumeName: pvc-a7016676-4c44-4f34-8c02-68908353555a
  status:
    accessModes:
    - ReadWriteOnce
    capacity:
      storage: 100Gi
    phase: Bound
- apiVersion: v1
  kind: PersistentVolumeClaim
  metadata:
    annotations:
      kubectl.kubernetes.io/last-applied-configuration: |
        {"apiVersion":"v1","kind":"PersistentVolumeClaim","metadata":{"annotations":{},"name":"openwebui-data","namespace":"vllm-chat"},"spec":{"accessModes":["ReadWriteOnce"],"resources":{"requests":{"storage":"10Gi"}},"storageClassName":"local-path"}}
      pv.kubernetes.io/bind-completed: "yes"
      pv.kubernetes.io/bound-by-controller: "yes"
      volume.beta.kubernetes.io/storage-provisioner: rancher.io/local-path
      volume.kubernetes.io/selected-node: srv-datalab
      volume.kubernetes.io/storage-provisioner: rancher.io/local-path
    creationTimestamp: "2026-01-04T14:35:54Z"
    finalizers:
    - kubernetes.io/pvc-protection
    name: openwebui-data
    namespace: vllm-chat
    resourceVersion: "57528351"
    uid: 2d326517-cf19-419a-b6e3-a05abb5e0bb3
  spec:
    accessModes:
    - ReadWriteOnce
    resources:
      requests:
        storage: 10Gi
    storageClassName: local-path
    volumeMode: Filesystem
    volumeName: pvc-2d326517-cf19-419a-b6e3-a05abb5e0bb3
  status:
    accessModes:
    - ReadWriteOnce
    capacity:
      storage: 10Gi
    phase: Bound
kind: List
metadata:
  resourceVersion: ""
